# Generated by Django 4.2.30 on 2026-05-09 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FactCheckResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.TextField()),
                ('input_url', models.URLField(blank=True)),
                ('verdict', models.CharField(choices=[('trusted', 'موثوق جداً'), ('no_evidence', 'لا يوجد أدلة كافية'), ('uncertain', 'غير مؤكد'), ('conflicting', 'مصادر متعارضة')], max_length=20)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('explanation', models.TextField()),
                ('key_claims', models.TextField(blank=True)),
                ('red_flags', models.TextField(blank=True)),
                ('sources_suggested', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fact_checks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'نتيجة تحقق',
                'verbose_name_plural': 'نتائج التحقق',
                'ordering': ['-created_at'],
            },
        ),
    ]
